kind: ConfigMap
metadata:
  name: argocd-cm
apiVersion: v1
data:
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
    - generate:
        args:
        - helm template . > all.yaml && kustomize build
        command:
        - sh
        - -c
      init:
        args:
        - helm init --client-only && helm dependency build
        command:
        - /bin/sh
        - -c
      name: kustomized-helm
  helm.repositories: |-
    - url: https://helm.goharbor.io
      name: harbor
    - url: https://strimzi.io/charts/
      name: strimzi
    - url: http://storage.googleapis.com/kubernetes-charts-incubator
      name: incubator
    - url: https://kubernetes-charts.storage.googleapis.com/
      name: stable
    - url: https://charts.bitnami.com/bitnami
      name: bitnami
    - url: https://charts.rook.io/release
      name: rook-release
    - url: https://helm.github.io/monocular
      name: monocular
  repositories: |
    - url: https://github.com/baloise-incubator/cluster-config.git
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /spec/additionalPrinterColumns/0/priority
        - /spec/additionalPrinterColumns/1/priority
        - /status/lastVersion
    build.openshift.io/BuildConfig:
      ignoreDifferences: |
        jsonPointers:
        - /status
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "Secrets"
      clusters:
      - https://kubernetes.default.svc
  dex.config: |-
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientID
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: baloise-incubator
          teamNameField: slug
  url: https://argocd.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
